name: Deploy tests

on:
  pull_request:

jobs:
  assess-file-changes:
    uses: catalystneuro/fee-lab-to-nwb/.github/workflows/assess-file-changes.yml@main

  detect-changelog-updates:
    needs: assess-file-changes
    name: Auto-detecting CHANGELOG.md updates
    runs-on: ubuntu-latest
    steps:
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'true' }}
        run: echo "CHANGELOG.md has been updated."
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'false' }}
        run: |
          echo "CHANGELOG.md has not been updated."
          0
